title: Pakshal Bohra
description: ""
email: pakshalbohra@gmail.com
email2: pakshal.bohra@distran.ch
url: "https://pakshal23.github.io"
github_username:  pakshal23
linkedin_username: pakshalbohra23

theme: minima
markdown: kramdown

header_pages:
  - cv.md
  - publications.md
